#!/usr/bin/python3

import os 
###################### Define the Paths and parameters ###########################

# Set paths and create some folders
flywheel_base ='/flywheel/v0/'
first_output_dir = '/firstOutput'
final_output_dir = os.path.join(flywheel_base, 'output')
manifest_file = os.path.join(flywheel_base, 'manifest.json')
config_path = os.path.join(flywheel_base, 'config.json')
os.system('mkdir %s'%first_output_dir)

###################Run Algorithm################################
   
num_img = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', 
           '12', '13', '14', '15', '16', '17', '18', '19', '20']

for i in num_img:   
    key_name = 'EPI_' + i
    folder_name = os.path.join(flywheel_base, 'input/%s' % key_name)
    if os.path.exists(folder_name):
        zip_name = os.listdir(folder_name)[0]    
        zip_file = os.path.join(folder_name, zip_name)
        subj_sess_name = zip_name[:-21]
        os.system('unzip -q %s -d %s/files/' % (zip_file, folder_name))
        new_folder_path = os.path.join(first_output_dir, key_name + '_' + subj_sess_name)
        os.system('mkdir %s' % new_folder_path)
        os.system('cp %s %s/' % (os.path.join(folder_name, 'files', os.listdir(os.path.join(folder_name, 'files'))[0]), new_folder_path))

################## Zip everything and output ##################################

# Zip and move the maps
print(os.listdir(first_output_dir))
os.system('cd %s; zip -q -r %s/concatenated_epi *'%(first_output_dir, final_output_dir))
